<ns0:test-suite xmlns:ns0="urn:model.allure.qatools.yandex.ru" start="1527404421827" stop="1527404422079">
  <name>test001</name>
  <labels/>
  <test-cases>
    <test-case start="1527404421827" status="passed" stop="1527404421839">
      <name>Test_001.test_adc[1]</name>
      <attachments/>
      <labels>
        <label name="severity" value="normal"/>
        <label name="thread" value="5072-MainThread"/>
        <label name="host" value="PC201509071647"/>
        <label name="framework" value="pytest"/>
        <label name="language" value="cpython3"/>
      </labels>
      <steps/>
    </test-case>
    <test-case start="1527404421841" status="failed" stop="1527404422076">
      <name>Test_001.test_adc[2]</name>
      <failure>
        <message>AssertionError: assert 2 != 2</message>
        <stack-trace>self = &lt;test001.Test_001 object at 0x00000000041E5898&gt;, a = 2

    @pytest.mark.parametrize("a",[1,2,3])
    def test_adc(self,a):
&gt;       assert a!=2
E       assert 2 != 2

scripts\test001.py:7: AssertionError</stack-trace>
      </failure>
      <attachments/>
      <labels>
        <label name="severity" value="normal"/>
        <label name="thread" value="5072-MainThread"/>
        <label name="host" value="PC201509071647"/>
        <label name="framework" value="pytest"/>
        <label name="language" value="cpython3"/>
      </labels>
      <steps/>
    </test-case>
    <test-case start="1527404422077" status="passed" stop="1527404422079">
      <name>Test_001.test_adc[3]</name>
      <attachments/>
      <labels>
        <label name="severity" value="normal"/>
        <label name="thread" value="5072-MainThread"/>
        <label name="host" value="PC201509071647"/>
        <label name="framework" value="pytest"/>
        <label name="language" value="cpython3"/>
      </labels>
      <steps/>
    </test-case>
  </test-cases>
</ns0:test-suite>
